### ISSUE TITLE
a little confuse about the readme.md

### ISSUE THREAD

**Issue by q8247990** [ahawker/crython#18]
the way to start the tab fot this version is 
`crython.start()`

**Comment by q8247990** [comment]
also, i fork the project cause i wanna dynamically add jobs to the default tab. So I change the job.py code to    achieve this goal. Hope it can be added to your code.

**Comment by ahawker** [comment]
Yes, the _public_ API is still open to changes and I won't lock it in until an official `1.0.0` release.

I can take a look at your "dynamic jobs" thing, but you're likely just better off creating your own `CronTab` instance and using that instead of trying to hack into the default one. The default one is just there for the simple cases. Anything more advanced, the caller will likely want full control over the object.

**Comment by q8247990** [comment]
thank you for noticing my issues(forgive my pool english). In my case, I have to add jobs into the crontab at anytime after the program is running (I offered a web interface to let others post jobs ).
